#!/bin/bash

# =================================================================
# GLOBAL CONFIGURATION
# =================================================================
# Define the central script version identifier
VERSION="2.2.1"

# =================================================================
# TEXT COLORS & STYLES
# =================================================================
GREEN='\033[32m'
RED='\033[31m'
YELLOW='\033[33m'
BLUE='\033[34m'
CYAN='\033[36m'
BOLD='\033[1m'
NEUTRAL='\033[0m'

# =================================================================
# INITIAL VARIABLES
# =================================================================
# Capture the current working directory path
current_dir=$(pwd)

# =================================================================
# SCRIPT EXECUTION
# =================================================================

# Step 1: Display the stylized CLI branding logo using the global version variable
echo -e "${BLUE}${BOLD} __      __      ___.                 .__     ${NEUTRAL}"
echo -e "${BLUE}${BOLD}/  \    /  \ ____\_ |__ _____    _____|  |__  ${NEUTRAL}"
echo -e "${CYAN}${BOLD}\   \/\/   // __ \| __ \\\\__  \  /  ___/  |  \ ${NEUTRAL}"
echo -e "${CYAN}${BOLD} \        /\  ___/| \_\ \/ __ \_\___ \|   Y  \\ ${NEUTRAL}"
echo -e "${GREEN}${BOLD}  \__/\  /  \___  >___  (____  /____  >___|  /${NEUTRAL}"
echo -e "${GREEN}${BOLD}       \/       \/    \/     \/     \/     \/ ${NEUTRAL} v${VERSION}"
echo -e "${CYAN}------------------------------------------------------------${NEUTRAL}"
echo ""

# Step 2: Perform environment scan and show current location
echo "Scanning environment..."
echo -e "Current working directory: ${BLUE}$current_dir${NEUTRAL}"
echo ""

# Step 3: Interactive prompt - Choose generation target location
target_dir="."
create_subfolder="n"

read -r -p "Do you want to create a dedicated subfolder for this project? (y/N): " location_choice
location_choice=$(echo "$location_choice" | tr '[:upper:]' '[:lower:]')

if [[ "$location_choice" == "y" || "$location_choice" == "yes" ]]; then
    create_subfolder="y"
    echo ""
    
    # Loop to handle project naming and potential directory conflicts interactively
    while true; do
        read -r -p "Enter your web project name: " project_name
        if [ -z "$project_name" ]; then
            project_name="web_project"
        fi
        target_dir="./$project_name"

        # Check if the directory already exists
        if [[ -e "$target_dir" ]]; then
            echo -e "${YELLOW}Conflict detected: '${project_name}' already exists.${NEUTRAL}"
            read -r -p "Do you want to overwrite it? [y/N]: " overwrite_choice
            overwrite_choice=$(echo "$overwrite_choice" | tr '[:upper:]' '[:lower:]')
            
            if [[ "$overwrite_choice" == "y" || "$overwrite_choice" == "yes" ]]; then
                echo -e "${RED}Removing existing directory...${NEUTRAL}"
                rm -rf "$target_dir"
                break # Conflict resolved by overwrite, exit the loop
            else
                echo -e "${CYAN}Let's pick another name.${NEUTRAL}"
                echo ""
                # Loop continues to ask for a new name
            fi
        else
            break # No conflict, exit the loop
        fi
    done
else
    # Dynamic detection: Use the name of the current folder as project name
    project_name=$(basename "$current_dir")
    echo -e "${YELLOW}Scaffolding will be deployed directly in the current directory.${NEUTRAL}"
fi
echo ""

echo "Initializing web project generation..."
echo ""

# Step 4: Create the main project root directory if a subfolder is requested
if [[ "$create_subfolder" == "y" ]]; then
    echo -e "Creating project root directory: ${YELLOW}$target_dir${NEUTRAL}..."
    mkdir "$target_dir"
    echo -e "-> ${GREEN}DONE${NEUTRAL}"
    echo ""
fi

# Step 5: Generate the required web architecture scaffolding (assets, src, styles)
echo -e "Generating project subdirectories inside: ${BLUE}$target_dir${NEUTRAL}..."
mkdir -p "$target_dir"/assets "$target_dir"/src "$target_dir"/styles
echo -e "-> ${GREEN}DONE${NEUTRAL}"
echo ""

# =================================================================
# FILE GENERATION & BOILERPLATE INJECTION
# =================================================================

# Step 6: Create and populate the global stylesheet with modern reset and dark theme variables
echo -e "Generating stylesheet: ${YELLOW}$target_dir/styles/style.css${NEUTRAL}..."
cat << EOF > "$target_dir"/styles/style.css
/* =================================================================
   Generated by Webash $VERSION - Core Stylesheet
   ================================================================= */

:root {
    --bg-color: #0f172a;
    --card-bg: #1e293b;
    --text-color: #f8fafc;
    --text-muted: #94a3b8;
    --primary: #38bdf8;
    --success: #4ade80;
}

/* Global Reset */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    background-color: var(--bg-color);
    color: var(--text-color);
    min-height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 20px;
}

.container {
    background-color: var(--card-bg);
    padding: 2.5rem;
    border-radius: 16px;
    box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.3);
    text-align: center;
    max-width: 500px;
    width: 100%;
    border: 1px solid rgba(255, 255, 255, 0.05);
}

h1 {
    color: var(--primary);
    font-size: 2.2rem;
    margin-bottom: 1rem;
}

p {
    color: var(--text-muted);
    font-size: 1.1rem;
    line-height: 1.6;
    margin-bottom: 1.5rem;
}

.badge {
    display: inline-block;
    background-color: rgba(74, 222, 128, 0.1);
    color: var(--success);
    padding: 0.5rem 1rem;
    border-radius: 9999px;
    font-size: 0.9rem;
    font-weight: 600;
}
EOF
echo -e "-> ${GREEN}DONE${NEUTRAL}"
echo ""

# Step 7: Create and populate the main JavaScript file with a DOMContentLoaded listener
echo -e "Generating main script: ${YELLOW}$target_dir/src/main.js${NEUTRAL}..."
cat << EOF > "$target_dir"/src/main.js
/**
 * Main Application Script - Generated by Webash $VERSION
 */

document.addEventListener('DOMContentLoaded', () => {
    console.log('🚀 Project "$project_name" successfully initialized!');
    
    // Add initialization logic and interactive code here
});
EOF
echo -e "-> ${GREEN}DONE${NEUTRAL}"
echo ""

# Step 8: Create and populate the index.html file with a structured semantic template
echo -e "Generating main template: ${YELLOW}$target_dir/index.html${NEUTRAL}..."
cat << EOF > "$target_dir"/index.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$project_name | Webash</title>
    <link rel="stylesheet" href="styles/style.css">
</head>
<body>

    <div class="container">
        <h1>$project_name</h1>
        <p>Your modern web structure has been successfully generated. Ready to start coding!</p>
        <span class="badge">Powered by Webash v$VERSION</span>
    </div>

    <script src="src/main.js"></script>
</body>
</html>
EOF
echo -e "-> ${GREEN}DONE${NEUTRAL}"
echo ""

# =================================================================
# FINALIZATION & ARCHITECTURE DISPLAY
# =================================================================
echo -e "${CYAN}-----------------------------------------------------------------------${NEUTRAL}"
echo -e "Your project ${BLUE}${BOLD}$project_name${NEUTRAL} has been created successfully!"
echo -e "${CYAN}-----------------------------------------------------------------------${NEUTRAL}"
echo ""

# Step 9: Display output directory tree structure depending on available system binaries
if command -v tree &> /dev/null; then
    tree "$target_dir"
else
    ls -R "$target_dir"
fi