#!/bin/bash

# =================================================================
# TEXT COLORS & STYLES
# =================================================================
GREEN='\033[32m'
RED='\033[31m'
YELLOW='\033[33m'
BLUE='\033[34m'
CYAN='\033[36m'
BOLD='\033[1m'
NEUTRAL='\033[0m'

# =================================================================
# INITIAL VARIABLES
# =================================================================
# Capture the current working directory path
current_dir=$(pwd)

# =================================================================
# SCRIPT EXECUTION
# =================================================================

# Step 1: Display the stylized CLI branding logo
echo -e "${BLUE}${BOLD} __      __      ___.                 .__     ${NEUTRAL}"
echo -e "${BLUE}${BOLD}/  \    /  \ ____\_ |__ _____    _____|  |__  ${NEUTRAL}"
echo -e "${CYAN}${BOLD}\   \/\/   // __ \| __ \\\\__  \  /  ___/  |  \ ${NEUTRAL}"
echo -e "${CYAN}${BOLD} \        /\  ___/| \_\ \/ __ \_\___ \|   Y  \\ ${NEUTRAL}"
echo -e "${GREEN}${BOLD}  \__/\  /  \___  >___  (____  /____  >___|  /${NEUTRAL}"
echo -e "${GREEN}${BOLD}       \/       \/    \/     \/     \/     \/ ${NEUTRAL} v2.0"
echo -e "${CYAN}------------------------------------------------------------${NEUTRAL}"
echo ""

# Step 2: Perform environment scan and show current location
echo "Scanning environment..."
echo -e "Current working directory: ${BLUE}$current_dir${NEUTRAL}"
echo ""

# Step 3: Prompt the user for the project name with a default fallback
read -r -p "Enter your web project name: " project_name
if [ -z "$project_name" ]; then
    project_name="web_project"
fi
echo ""

echo "Initializing web project generation..."
echo ""

# Step 4: Check for existing directory conflicts and clean up if necessary
if [[ -e "$project_name" ]]; then
    echo -e "${RED}Conflict detected: A directory with this name already exists. Cleaning up...${NEUTRAL}"
    rm -rf "$project_name"
fi

# Step 5: Create the main project root directory
echo -e "Creating project root directory: ${YELLOW}$project_name${NEUTRAL}..."
mkdir "$project_name"
echo -e "-> ${GREEN}DONE${NEUTRAL}"
echo ""

# Step 6: Generate the required web architecture scaffolding (src, assets, styles)
echo -e "Generating project subdirectories: ${YELLOW}src${NEUTRAL}, ${YELLOW}assets${NEUTRAL}, and ${YELLOW}styles${NEUTRAL}..."
mkdir -p "$project_name"/src "$project_name"/assets "$project_name"/styles
echo -e "-> ${GREEN}DONE${NEUTRAL}"
echo ""

# =================================================================
# FILE GENERATION & BOILERPLATE INJECTION
# =================================================================

# Step 7: Create and populate the global stylesheet with modern reset and dark theme variables
echo -e "Generating stylesheet: ${YELLOW}styles/style.css${NEUTRAL}..."
cat << EOF > "$project_name"/styles/style.css
/* =================================================================
   Generated by Webash 2.0 - Core Stylesheet
   ================================================================= */

:root {
    --bg-color: #0f172a;
    --card-bg: #1e293b;
    --text-color: #f8fafc;
    --text-muted: #94a3b8;
    --primary: #38bdf8;
    --success: #4ade80;
}

/* Global Reset */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
    background-color: var(--bg-color);
    color: var(--text-color);
    min-height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 20px;
}

.container {
    background-color: var(--card-bg);
    padding: 2.5rem;
    border-radius: 16px;
    box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.3);
    text-align: center;
    max-width: 500px;
    width: 100%;
    border: 1px solid rgba(255, 255, 255, 0.05);
}

h1 {
    color: var(--primary);
    font-size: 2.2rem;
    margin-bottom: 1rem;
}

p {
    color: var(--text-muted);
    font-size: 1.1rem;
    line-height: 1.6;
    margin-bottom: 1.5rem;
}

.badge {
    display: inline-block;
    background-color: rgba(74, 222, 128, 0.1);
    color: var(--success);
    padding: 0.5rem 1rem;
    border-radius: 9999px;
    font-size: 0.9rem;
    font-weight: 600;
}
EOF
echo -e "-> ${GREEN}DONE${NEUTRAL}"
echo ""

# Step 8: Create and populate the main JavaScript file with a DOMContentLoaded listener
echo -e "Generating main script: ${YELLOW}src/main.js${NEUTRAL}..."
cat << EOF > "$project_name"/src/main.js
/**
 * Main Application Script - Generated by Webash 2.0
 */

document.addEventListener('DOMContentLoaded', () => {
    console.log('🚀 Project "$project_name" successfully initialized!');
    
    // Add initialization logic and interactive code here
});
EOF
echo -e "-> ${GREEN}DONE${NEUTRAL}"
echo ""

# Step 9: Create and populate the index.html file with a structured semantic template
echo -e "Generating main template: ${YELLOW}index.html${NEUTRAL}..."
cat << EOF > "$project_name"/index.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$project_name | Webash</title>
    <link rel="stylesheet" href="styles/style.css">
</head>
<body>

    <div class="container">
        <h1>$project_name</h1>
        <p>Your modern web structure has been successfully generated. Ready to start coding!</p>
        <span class="badge">Powered by Webash v2.0</span>
    </div>

    <script src="src/main.js"></script>
</body>
</html>
EOF
echo -e "-> ${GREEN}DONE${NEUTRAL}"
echo ""

# =================================================================
# FINALIZATION & ARCHITECTURE DISPLAY
# =================================================================
echo -e "${CYAN}-----------------------------------------------------------------------${NEUTRAL}"
echo -e "Your project ${BLUE}${BOLD}$project_name${NEUTRAL} has been created successfully!"
echo -e "${CYAN}-----------------------------------------------------------------------${NEUTRAL}"
echo ""

# Step 10: Display output directory tree structure depending on available system binaries
if command -v tree &> /dev/null; then
    tree "$project_name"
else
    ls -R "$project_name"
fi